apiVersion: apps/v1
kind: Deployment
metadata:
  name: '{{ .Release.Name }}-active-directory'
  labels:
    katenary.io/component: active-directory
    katenary.io/project: '{{ .Chart.Name }}'
    katenary.io/release: '{{ .Release.Name }}'
  annotations:
    katenary.io/docker-compose-sha1: 025e91e17029d80290ac060df710f901b49c55cb
    katenary.io/version: 2.0.0-beta2
spec:
  replicas: 1
  selector:
    matchLabels:
      katenary.io/component: active-directory
      katenary.io/release: '{{ .Release.Name }}'
  template:
    metadata:
      labels:
        katenary.io/component: active-directory
        katenary.io/release: '{{ .Release.Name }}'
    spec:
      containers:
        - name: active-directory
          image: '{{ .Values.repository.image }}{{ if ne .Values.repository.tag "" }}:{{ .Values.repository.tag }}{{ end }}'
          ports:
            - name: nossl-port
              containerPort: 389
            - name: ssl-port
              containerPort: 636
          env:
          - name: REALM
            value: '{{ .Values.domain }}'
          - name: DOMAIN
            value: '{{ splitList "." .Values.domain  | first }}'
          - name: ADMINPASS
            value: '{{ .Values.adminpass }}'
          - name: INSECURE_LDAP
            value: 'true'
