apiVersion: v1
kind: Service
metadata:
  name: '{{ .Release.Name }}-active-directory'
  labels:
    katenary.io/component: active-directory
    katenary.io/project: '{{ .Chart.Name }}'
    katenary.io/release: '{{ .Release.Name }}'
  annotations:
    katenary.io/docker-compose-sha1: 025e91e17029d80290ac060df710f901b49c55cb
    katenary.io/version: 2.0.0-beta2
spec:
  selector:
    katenary.io/component: active-directory
    katenary.io/release: '{{ .Release.Name }}'
  ports:
    - name: nossl-port
      protocol: TCP
      port: 389
      targetPort: 389
    - name: ssl-port
      protocol: TCP
      port: 636
      targetPort: 636