apiVersion: v1
kind: Service
metadata:
  name: {{ template "ldap.fullname" . }}
  labels:
    app: {{ include "ldap.name" . | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
{{- if .Values.service.annotations }}
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ template "ldap.name" . }}
    release: {{ .Release.Name }}
  ports:
    - name: nossl-port
      targetPort: 389
      {{- if eq .Values.service.type  "NodePort" }}
      port: 389
      nodePort: {{ .Values.service.nosslpPort }}      
      {{- else }}
      port: {{ .Values.service.nosslpPort }}
      {{- end }}
    - name: ssl-port
      targetPort: 636
      {{- if eq .Values.service.type  "NodePort" }}
      port: 636
      nodePort: {{ .Values.service.sslPort }}
      {{- else }}
      port: {{ .Values.service.sslPort }}
      {{- end }}