apiVersion: v1
kind: Service
metadata:
  name: ldap-lb
  namespace: d4n-utils
spec:
  selector:
    app: ldap
  type: LoadBalancer
  ports:
  - name: lbnosslport
    port: 389
    targetPort: 389 
  - name: lbsslport
    port: 636
    targetPort: 636 

--- 
apiVersion: v1
kind: Service
metadata:
  name: ldap-np
  namespace: d4n-utils
spec:
  selector:
    app: ldap
  type: NodePort
  ports:
  - name: lbnosslport
    port: 389
    targetPort: 389
    nodePort: 31389 
  - name: lbsslport
    port: 636
    targetPort: 636
    nodePort: 31636 