repository:
  image: smblds/smblds
  tag: ""

properties:
  domain: data4now.org
  adminpass: Data4Now

service:
  sslPort: 636        # if type is LoadBalancer this should be 30000-32767
  nosslpPort: 389     # if type is LoadBalancer this should be 30000-32767
  type: ClusterIP    
  annotations: {}


ingress:
  enabled: false
  ingressClassName: apisix
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
    # kubernetes.io/ingress.allow-http: "false"
    # kubernetes.io/ingress.global-static-ip-name: ""
    # nginx.ingress.kubernetes.io/secure-backends: "true"
    # nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    # nginx.ingress.kubernetes.io/whitelist-source-range: 0.0.0.0/0
  nosslHost: nossl-exemple.local
  sslHost: ssl-example.local
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local
